# Generated by Django 5.0.7 on 2024-07-18 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_subscriptionplan_duration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriptionplan',
            old_name='subname',
            new_name='name',
        ),
    ]
