# Generated by Django 5.0.7 on 2024-07-18 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_rename_subname_subscriptionplan_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubscription',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
