# Generated by Django 5.0.7 on 2024-08-09 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_rename_subname_subscriptionplan_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('businessName', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='MeetingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventName', models.CharField(max_length=255)),
                ('duration', models.IntegerField()),
                ('locationType', models.CharField(max_length=255)),
                ('locationUrl', models.URLField()),
            ],
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ScheduledMeeting',
            fields=[
                ('businessName', models.CharField(max_length=255)),
                ('businessEmail', models.EmailField(max_length=254)),
                ('selectedTime', models.CharField(max_length=255)),
                ('selectedDate', models.DateField()),
                ('duration', models.IntegerField()),
                ('locationUrl', models.URLField()),
                ('userName', models.CharField(max_length=255)),
                ('userEmail', models.EmailField(max_length=254)),
                ('userNote', models.TextField()),
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('eventId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.meetingevent')),
            ],
        ),
    ]
