# Generated by Django 5.0.7 on 2024-07-30 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_usersubscription_start_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventName', models.CharField(max_length=255)),
                ('duration', models.IntegerField()),
                ('locationType', models.CharField(max_length=255)),
                ('locationUrl', models.URLField()),
                ('themeColor', models.CharField(max_length=7)),
                ('createdBy', models.EmailField(max_length=254)),
            ],
        ),
    ]
