# Generated by Django 5.0.7 on 2024-07-30 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_locationoption'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LocationOption',
        ),
    ]
